---
branches:
  except:
  - refactor
  - gh-pages
sudo: false
language: ruby
script: "bundle exec rake validate && bundle exec rake lint && bundle exec rake spec SPEC_OPTS='--format documentation'"
bundler_args: --without rake
matrix:
  fast_finish: true
  include:
    - rvm: 1.8.7
      env: PUPPET_GEM_VERSION="~> 2.7.0"
    - rvm: 1.8.7
      env: PUPPET_GEM_VERSION="~> 3.0"
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION="~> 3.0"
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION="~> 3.0"
    - rvm: 2.1.0
      env: PUPPET_GEM_VERSION="~> 3.0"
    - rvm: 2.1.0
      env: PUPPET_GEM_VERSION="~> 3.5.0" FUTURE_PARSER="yes"
  allow_failures:
    - rvm: 1.8.7
      env: PUPPET_GEM_VERSION="~> 2.7.0"
    - rvm: 1.8.7
      env: PUPPET_GEM_VERSION="~> 3.0"
    - rvm: 2.1.0
      env: PUPPET_GEM_VERSION="~> 3.5.0" FUTURE_PARSER="yes"
notifications:
  email: false  
